version: '3.3'
services:
    jenkins:
      build: .
      # image: jenkins/jenkins:lts
      ports:
        - '18080:8080'
        - '50000:50000'
      volumes:
        - jenkins_home:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
